-- Macro that generates filter query for all source tables to exclude deleted records 
--{{ generate_delete_query (["source ('SAP_ECC','EKKO')", "source ('SAP_ECC','EKPO')"]) }}

-- Start of business logic 
cv_purchasing_document_consolidation as

(SELECT EKKO.EBELN AS PO_NUMNER, 
		EKPO.EBELP AS PO_ITEM, 
		EKKO.BUKRS AS COMPANY_CODE, 
		EKKO.LIFNR AS SUPPLIER, 
		EKKO.AEDAT AS PO_CREATED_DATE,
		EKKO.BEDAT AS PO_DOCUMENTED_DATE, 
		EKPO.AEDAT AS PO_ITEM_CHANGED_DATE,
		EKPO.MATNR AS MATERIAL_NUMBER, 
		EKPO.WERKS AS PLANT, 
		EKPO.MENGE AS PO_QUANTITY, 
		EKPO.MEINS AS UNIT_OF_MEASURE, 
		EKPO.PEINH AS UNIT_PRICE,
		EKPO.NETPR AS PO_NET_PRICE, 
		EKPO.NETWR AS PO_NET_VALUE, 
		EKPO.BRTWR AS PO_GROSS_VALUE
		
FROM SAP_ECC_EKKO AS EKKO
LEFT JOIN 
SAP_ECC_EKPO AS EKPO

ON EKKO.MANDT = EKPO.MANDT
AND EKKO.EBELN = EKPO.EBELN)

-- Enforcing datatype and lengths for target table in snowflake----
SELECT PO_NUMNER::VARCHAR(10) AS PO_NUMNER,
       PO_ITEM::VARCHAR(5) AS PO_ITEM,
       COMPANY_CODE::VARCHAR(4) AS COMPANY_CODE,
       SUPPLIER::VARCHAR(10) AS SUPPLIER,
       PO_CREATED_DATE::VARCHAR(8) AS PO_CREATED_DATE,
       PO_DOCUMENTED_DATE::VARCHAR(8) AS PO_DOCUMENTED_DATE,
       PO_ITEM_CHANGED_DATE::VARCHAR(8) AS PO_ITEM_CHANGED_DATE,
       MATERIAL_NUMBER::VARCHAR(17) AS MATERIAL_NUMBER,
       PLANT::VARCHAR(4) AS PLANT,
       PO_QUANTITY::NUMBER(21, 2) AS PO_QUANTITY,
       UNIT_OF_MEASURE::VARCHAR(3) AS UNIT_OF_MEASURE,
       UNIT_PRICE::NUMBER(21, 2) AS UNIT_PRICE,
       PO_NET_PRICE::NUMBER(21, 2) AS PO_NET_PRICE,
       PO_NET_VALUE::NUMBER(21, 2) AS PO_NET_VALUE,
       PO_GROSS_VALUE::NUMBER(21, 2) AS PO_GROSS_VALUE
FROM cv_purchasing_document_consolidation
